//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfSignedX509OpenSslNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ca.cer")]
        public string caCertificateFileLocation {
            get {
                return ((string)(this["caCertificateFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\users\\brian\\documents\\github\\notejs-proxy\\selfsignedx509opensslnet\\\\bin\\capkey" +
            ".key")]
        public string caPrivateKeyFileLocation {
            get {
                return ((string)(this["caPrivateKeyFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\users\\brian\\documents\\github\\nodejs-proxy\\selfsignedx509opensslnet\\\\bin\\csr.cs" +
            "r")]
        public string csrFileLocation {
            get {
                return ((string)(this["csrFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\users\\brian\\documents\\github\\nodejs-proxy\\selfsignedx509opensslnet\\\\pkey.key")]
        public string csrPrivateKeyFileLocation {
            get {
                return ((string)(this["csrPrivateKeyFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string csrPrivateKeyPassword {
            get {
                return ((string)(this["csrPrivateKeyPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("caPassword")]
        public string caPrivateKeyPassword {
            get {
                return ((string)(this["caPrivateKeyPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\users\\brian\\documents\\github\\nodejs-proxy\\selfsignedx509opensslnet\\new cert.ce" +
            "r")]
        public string SignedCertificateFileLocation {
            get {
                return ((string)(this["SignedCertificateFileLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenSSL.cnf")]
        public string OpenSslConfigurationFileName {
            get {
                return ((string)(this["OpenSslConfigurationFileName"]));
            }
            set {
                this["OpenSslConfigurationFileName"] = value;
            }
        }
    }
}
